server {
    server_name msw.bizo.technology;
    root /var/www/msw/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/msw.bizo.technology/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/msw.bizo.technology/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = msw.bizo.technology) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name msw.bizo.technology;
    return 404;
}
